/* The following code was generated by JFlex 1.4.1 on 22.08.09 17:42 */

package net.ishchenko.idea.nginx.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import net.ishchenko.idea.nginx.lexer.NginxElementTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 22.08.09 17:42 from the specification file
 * <tt>G:/Work/nginx maia/src/net/ishchenko/idea/nginx/lexer/nginx.flex</tt>
 */
final class _NginxLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DIRECTIVE_VALUE = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\31\1\0\1\1\1\1\22\0\1\2\2\0\1\30"+
    "\1\27\2\0\1\35\23\0\1\32\43\0\1\24\1\0\1\15\1\34"+
    "\1\14\1\34\1\7\1\20\1\26\1\3\1\16\2\34\1\12\1\22"+
    "\1\17\1\13\1\5\1\34\1\10\1\6\1\4\1\21\1\11\1\34"+
    "\1\25\1\23\1\34\1\36\1\0\1\33\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\12\1\1\3\1\4\1\5\1\6"+
    "\2\2\1\7\1\10\1\11\1\4\1\12\7\1\1\13"+
    "\4\1\2\3\1\0\1\14\1\0\1\15\11\1\1\6"+
    "\31\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\174\0\233\0\272\0\331"+
    "\0\370\0\u0117\0\u0136\0\u0155\0\u0174\0\u0193\0\u01b2\0\u01d1"+
    "\0\u01f0\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c\0\u01f0\0\u01f0"+
    "\0\u028b\0\u01f0\0\u02aa\0\u02c9\0\u02e8\0\u0307\0\u0326\0\u0345"+
    "\0\u0364\0\76\0\u0383\0\u03a2\0\u03c1\0\u03e0\0\u03ff\0\u01f0"+
    "\0\u041e\0\u01f0\0\u028b\0\u01f0\0\u043d\0\u045c\0\u047b\0\u049a"+
    "\0\u04b9\0\u04d8\0\u04f7\0\u0516\0\u0535\0\u01f0\0\u0554\0\u0573"+
    "\0\u0592\0\u05b1\0\u05d0\0\u05ef\0\u060e\0\u062d\0\u064c\0\u066b"+
    "\0\u068a\0\u06a9\0\u06c8\0\u06e7\0\u0706\0\u0725\0\u0744\0\u0763"+
    "\0\u0782\0\u07a1\0\u07c0\0\u07df\0\u07fe\0\u081d\0\u083c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\10\1\11"+
    "\2\3\1\12\1\3\1\13\1\3\1\14\2\3\1\15"+
    "\1\16\3\3\1\17\1\3\1\20\1\4\1\21\1\22"+
    "\1\3\2\21\1\23\1\24\1\25\24\23\1\26\1\20"+
    "\1\24\1\27\1\30\1\23\1\31\1\32\1\3\2\0"+
    "\25\3\4\0\1\3\3\0\2\4\26\0\1\4\6\0"+
    "\1\4\1\5\25\0\1\20\1\4\5\0\1\3\2\0"+
    "\1\3\1\33\23\3\4\0\1\3\2\0\1\3\2\0"+
    "\20\3\1\34\4\3\4\0\1\3\2\0\1\3\2\0"+
    "\4\3\1\35\20\3\4\0\1\3\2\0\1\3\2\0"+
    "\6\3\1\36\16\3\4\0\1\3\2\0\1\3\2\0"+
    "\10\3\1\37\2\3\1\40\11\3\4\0\1\3\2\0"+
    "\1\3\2\0\1\41\24\3\4\0\1\3\2\0\1\3"+
    "\2\0\15\3\1\42\1\3\1\43\5\3\4\0\1\3"+
    "\2\0\1\3\2\0\2\3\1\44\22\3\4\0\1\3"+
    "\2\0\1\3\2\0\12\3\1\45\12\3\4\0\1\3"+
    "\2\0\1\3\2\0\4\3\1\46\20\3\4\0\1\3"+
    "\2\0\31\47\1\50\5\47\37\0\1\23\2\0\24\23"+
    "\1\51\4\0\1\23\2\0\1\52\2\24\24\52\2\0"+
    "\1\24\2\0\1\52\2\0\1\52\1\24\1\25\24\52"+
    "\1\0\1\20\1\24\2\0\1\52\5\0\24\26\5\0"+
    "\1\26\2\0\35\53\1\54\1\53\1\3\2\0\1\3"+
    "\1\55\23\3\4\0\1\3\2\0\1\3\2\0\2\3"+
    "\1\56\22\3\4\0\1\3\2\0\1\3\2\0\5\3"+
    "\1\57\17\3\4\0\1\3\2\0\1\3\2\0\4\3"+
    "\1\60\20\3\4\0\1\3\2\0\1\3\2\0\11\3"+
    "\1\61\13\3\4\0\1\3\2\0\1\3\2\0\17\3"+
    "\1\62\5\3\4\0\1\3\2\0\1\3\2\0\12\3"+
    "\1\63\12\3\4\0\1\3\2\0\1\3\2\0\12\3"+
    "\1\55\12\3\4\0\1\3\2\0\1\3\2\0\3\3"+
    "\1\64\21\3\4\0\1\3\2\0\1\3\2\0\2\3"+
    "\1\42\10\3\1\65\11\3\4\0\1\3\2\0\1\3"+
    "\2\0\10\3\1\42\14\3\4\0\1\3\2\0\31\47"+
    "\1\0\5\47\3\66\24\0\5\66\1\0\2\66\1\3"+
    "\2\0\2\3\1\42\22\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\67\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\6\3\1\70\16\3\4\0\1\3\2\0\1\3"+
    "\2\0\14\3\1\71\10\3\4\0\1\3\2\0\1\3"+
    "\2\0\12\3\1\72\12\3\4\0\1\3\2\0\1\3"+
    "\2\0\13\3\1\73\11\3\4\0\1\3\2\0\1\3"+
    "\2\0\5\3\1\74\17\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\75\23\3\4\0\1\3\2\0\1\3"+
    "\2\0\7\3\1\42\15\3\4\0\1\3\2\0\1\3"+
    "\2\0\3\3\1\42\21\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\76\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\67\23\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\77\23\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\100\23\3\4\0\1\3\2\0\1\3"+
    "\2\0\3\3\1\101\21\3\4\0\1\3\2\0\1\3"+
    "\2\0\5\3\1\102\17\3\4\0\1\3\2\0\1\3"+
    "\2\0\5\3\1\42\17\3\4\0\1\3\2\0\1\3"+
    "\2\0\13\3\1\103\11\3\4\0\1\3\2\0\1\3"+
    "\2\0\21\3\1\104\3\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\105\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\106\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\10\3\1\107\14\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\110\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\111\23\3\4\0\1\3\2\0\1\3"+
    "\2\0\12\3\1\112\12\3\4\0\1\3\2\0\1\3"+
    "\2\0\14\3\1\42\10\3\4\0\1\3\2\0\1\3"+
    "\2\0\22\3\1\113\2\3\4\0\1\3\2\0\1\3"+
    "\2\0\21\3\1\114\3\3\4\0\1\3\2\0\1\3"+
    "\2\0\17\3\1\42\5\3\4\0\1\3\2\0\1\3"+
    "\2\0\11\3\1\115\13\3\4\0\1\3\2\0\1\3"+
    "\2\0\17\3\1\43\5\3\4\0\1\3\2\0\1\3"+
    "\2\0\4\3\1\116\20\3\4\0\1\3\2\0\1\3"+
    "\2\0\2\3\1\117\22\3\4\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\42\23\3\4\0\1\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2139];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\16\1\2\11\4\1\2\11\1\1\1\11\15\1"+
    "\1\11\1\0\1\11\1\0\1\11\11\1\1\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  _NginxLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _NginxLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 94) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return NginxElementTypes.CLOSING_BRACE;
          }
        case 14: break;
        case 6: 
          { //the idea is to distinguish:
                                                // 1) asd$ as value "asd$"
                                                // 2) asd$qwe as value "asd" and variable "$qwe"
                                                //thus, I include dollar and tail and cut the tail
                                                //if you find any easier solution - advise me, please
                                                int indexOfDollar = yytext().toString().indexOf("$");
                                                if (indexOfDollar >= 0) {
                                                    yypushback(yylength() - indexOfDollar - 1);
                                                }

                                                return NginxElementTypes.DIRECTIVE_VALUE;
          }
        case 15: break;
        case 3: 
          { return NginxElementTypes.COMMENT;
          }
        case 16: break;
        case 10: 
          { yybegin(YYINITIAL); return NginxElementTypes.OPENING_BRACE;
          }
        case 17: break;
        case 1: 
          { yybegin(DIRECTIVE_VALUE); return NginxElementTypes.DIRECTIVE_NAME;
          }
        case 18: break;
        case 9: 
          { yybegin(YYINITIAL); return NginxElementTypes.CLOSING_BRACE;
          }
        case 19: break;
        case 2: 
          { return NginxElementTypes.WHITE_SPACE;
          }
        case 20: break;
        case 8: 
          { yybegin(YYINITIAL); return NginxElementTypes.SEMICOLON;
          }
        case 21: break;
        case 11: 
          { yybegin(DIRECTIVE_VALUE); return NginxElementTypes.CONTEXT_NAME;
          }
        case 22: break;
        case 12: 
          { yypushback(1); return NginxElementTypes.VALUE_WHITE_SPACE;
          }
        case 23: break;
        case 4: 
          { return NginxElementTypes.BAD_CHARACTER;
          }
        case 24: break;
        case 13: 
          { return NginxElementTypes.DIRECTIVE_STRING_VALUE;
          }
        case 25: break;
        case 7: 
          { return NginxElementTypes.INNER_VARIABLE;
          }
        case 26: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
