/* The following code was generated by JFlex 1.4.3 on 17/04/16 8:38 AM */

package net.ishchenko.idea.nginx.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 17/04/16 8:38 AM from the specification file
 * <tt>/home/deadleg/git/idea-nginx/src/net/ishchenko/idea/nginx/lexer/nginx.flex</tt>
 */
final class _NginxLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DIRECTIVE_VALUE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\35\1\0\1\1\1\1\22\0\1\2\1\0\1\33"+
    "\1\34\1\40\2\0\1\42\23\0\1\36\43\0\1\24\1\0\1\15"+
    "\1\27\1\14\1\32\1\7\1\20\1\26\1\3\1\16\1\41\1\30"+
    "\1\12\1\22\1\17\1\13\1\5\1\41\1\10\1\6\1\4\1\21"+
    "\1\11\1\31\1\25\1\23\1\41\1\43\1\0\1\37\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\15\1\1\3\1\4\1\5\1\6"+
    "\2\2\1\4\1\7\1\10\1\11\1\4\1\12\15\1"+
    "\1\13\5\1\2\3\1\0\1\14\1\0\1\15\1\0"+
    "\20\1\1\6\56\1\1\13\15\1\1\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\u0264\0\u0288\0\u02ac\0\u02ac\0\u02d0\0\u02f4\0\u0318"+
    "\0\u033c\0\u02ac\0\u02ac\0\u0360\0\u0384\0\u02ac\0\u03a8\0\u03cc"+
    "\0\u03f0\0\u0414\0\u0438\0\u045c\0\u0480\0\u04a4\0\u04c8\0\u04ec"+
    "\0\u0510\0\u0534\0\u0558\0\110\0\u057c\0\u05a0\0\u05c4\0\u05e8"+
    "\0\u060c\0\u0630\0\u02ac\0\u0654\0\u02ac\0\u033c\0\u02ac\0\u0384"+
    "\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c\0\u0750\0\u0774"+
    "\0\u0798\0\u07bc\0\u07e0\0\u0804\0\u0828\0\u084c\0\u0870\0\u0894"+
    "\0\u02ac\0\u08b8\0\u08dc\0\u0900\0\u0924\0\u0948\0\u096c\0\u0990"+
    "\0\u09b4\0\u09d8\0\u09fc\0\u0a20\0\u0a44\0\u0a68\0\u0a8c\0\u0ab0"+
    "\0\u0ad4\0\u0af8\0\u0b1c\0\u0b40\0\u0b64\0\u0b88\0\u0bac\0\u0bd0"+
    "\0\u0bf4\0\u0c18\0\u0c3c\0\u0c60\0\u0c84\0\u0ca8\0\u0ccc\0\u0cf0"+
    "\0\u0d14\0\u0d38\0\u0d5c\0\u0d80\0\u0da4\0\u0dc8\0\u0dec\0\u0e10"+
    "\0\u0e34\0\u0e58\0\u0e7c\0\u0ea0\0\u0ec4\0\u0ee8\0\u0f0c\0\u06e4"+
    "\0\u0f30\0\u0f54\0\u0f78\0\u0f9c\0\u0fc0\0\u0fe4\0\u1008\0\u102c"+
    "\0\u1050\0\u1074\0\u1098\0\u10bc\0\u10e0\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\10\1\11"+
    "\1\12\1\3\1\13\1\3\1\14\1\15\1\16\2\3"+
    "\1\17\1\20\3\3\1\21\1\22\4\3\1\23\1\4"+
    "\1\24\1\25\2\3\2\24\1\26\1\27\1\30\30\26"+
    "\1\31\1\23\1\27\1\32\1\33\1\34\1\26\1\35"+
    "\1\36\1\3\2\0\31\3\4\0\2\3\3\0\2\4"+
    "\32\0\1\4\7\0\1\4\1\5\31\0\1\23\1\4"+
    "\6\0\1\3\2\0\1\3\1\37\2\3\1\40\24\3"+
    "\4\0\2\3\2\0\1\3\2\0\20\3\1\41\10\3"+
    "\4\0\2\3\2\0\1\3\2\0\3\3\1\42\1\43"+
    "\24\3\4\0\2\3\2\0\1\3\2\0\6\3\1\44"+
    "\22\3\4\0\2\3\2\0\1\3\2\0\4\3\1\45"+
    "\24\3\4\0\2\3\2\0\1\3\2\0\10\3\1\46"+
    "\2\3\1\47\15\3\4\0\2\3\2\0\1\3\2\0"+
    "\1\50\7\3\1\51\20\3\4\0\2\3\2\0\1\3"+
    "\2\0\11\3\1\52\17\3\4\0\2\3\2\0\1\3"+
    "\2\0\14\3\1\53\1\54\1\3\1\55\11\3\4\0"+
    "\2\3\2\0\1\3\2\0\2\3\1\56\26\3\4\0"+
    "\2\3\2\0\1\3\2\0\12\3\1\57\16\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\60\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\10\3\1\61\20\3\4\0"+
    "\2\3\2\0\35\62\1\63\6\62\44\0\1\26\2\0"+
    "\30\26\5\0\1\64\1\26\2\0\1\65\2\27\30\65"+
    "\2\0\1\27\2\0\2\65\2\0\1\65\1\27\1\30"+
    "\30\65\1\0\1\23\1\27\2\0\2\65\2\0\33\66"+
    "\1\67\10\66\3\0\30\34\6\0\1\34\2\0\42\70"+
    "\1\67\1\70\1\3\2\0\1\3\1\71\27\3\4\0"+
    "\2\3\2\0\1\3\2\0\12\3\1\72\16\3\4\0"+
    "\2\3\2\0\1\3\2\0\2\3\1\73\26\3\4\0"+
    "\2\3\2\0\1\3\2\0\7\3\1\74\21\3\4\0"+
    "\2\3\2\0\1\3\2\0\1\3\1\74\3\3\1\75"+
    "\23\3\4\0\2\3\2\0\1\3\2\0\4\3\1\76"+
    "\24\3\4\0\2\3\2\0\1\3\2\0\26\3\1\77"+
    "\2\3\4\0\2\3\2\0\1\3\2\0\11\3\1\100"+
    "\11\3\1\74\5\3\4\0\2\3\2\0\1\3\2\0"+
    "\17\3\1\101\11\3\4\0\2\3\2\0\1\3\2\0"+
    "\12\3\1\102\16\3\4\0\2\3\2\0\1\3\2\0"+
    "\14\3\1\103\14\3\4\0\2\3\2\0\1\3\2\0"+
    "\11\3\1\104\17\3\4\0\2\3\2\0\1\3\2\0"+
    "\13\3\1\105\15\3\4\0\2\3\2\0\1\3\2\0"+
    "\12\3\1\71\16\3\4\0\2\3\2\0\1\3\2\0"+
    "\3\3\1\106\25\3\4\0\2\3\2\0\1\3\2\0"+
    "\2\3\1\54\10\3\1\107\15\3\4\0\2\3\2\0"+
    "\1\3\2\0\10\3\1\54\20\3\4\0\2\3\2\0"+
    "\1\3\2\0\27\3\1\110\1\3\4\0\2\3\2\0"+
    "\35\62\1\0\6\62\3\111\30\0\6\111\1\0\2\111"+
    "\1\3\2\0\2\3\1\54\26\3\4\0\2\3\2\0"+
    "\1\3\2\0\27\3\1\112\1\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\113\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\21\3\1\114\7\3\4\0\2\3\2\0"+
    "\1\3\2\0\6\3\1\115\22\3\4\0\2\3\2\0"+
    "\1\3\2\0\14\3\1\116\14\3\4\0\2\3\2\0"+
    "\1\3\2\0\5\3\1\117\23\3\4\0\2\3\2\0"+
    "\1\3\2\0\12\3\1\120\16\3\4\0\2\3\2\0"+
    "\1\3\2\0\13\3\1\121\15\3\4\0\2\3\2\0"+
    "\1\3\2\0\5\3\1\122\23\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\123\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\124\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\125\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\126\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\7\3\1\54\21\3\4\0\2\3\2\0"+
    "\1\3\2\0\20\3\1\127\10\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\130\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\3\3\1\54\25\3\4\0\2\3\2\0"+
    "\1\3\2\0\24\3\1\131\4\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\132\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\113\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\13\3\1\133\15\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\134\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\135\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\3\3\1\136\25\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\137\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\3\3\1\140\25\3\4\0\2\3\2\0"+
    "\1\3\2\0\21\3\1\141\7\3\4\0\2\3\2\0"+
    "\1\3\2\0\5\3\1\142\23\3\4\0\2\3\2\0"+
    "\1\3\2\0\21\3\1\143\7\3\4\0\2\3\2\0"+
    "\1\3\2\0\5\3\1\127\23\3\4\0\2\3\2\0"+
    "\1\3\2\0\20\3\1\144\10\3\4\0\2\3\2\0"+
    "\1\3\2\0\5\3\1\54\23\3\4\0\2\3\2\0"+
    "\1\3\2\0\1\3\1\145\27\3\4\0\2\3\2\0"+
    "\1\3\2\0\13\3\1\146\15\3\4\0\2\3\2\0"+
    "\1\3\2\0\21\3\1\147\7\3\4\0\2\3\2\0"+
    "\1\3\2\0\4\3\1\150\24\3\4\0\2\3\2\0"+
    "\1\3\2\0\14\3\1\151\14\3\4\0\2\3\2\0"+
    "\1\3\2\0\3\3\1\74\25\3\4\0\2\3\2\0"+
    "\1\3\2\0\24\3\1\131\1\3\1\152\2\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\153\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\15\3\1\154\13\3\4\0"+
    "\2\3\2\0\1\3\2\0\21\3\1\155\7\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\74\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\10\3\1\156\20\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\157\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\1\3\1\160\27\3\4\0"+
    "\2\3\2\0\1\3\2\0\1\3\1\74\27\3\4\0"+
    "\2\3\2\0\1\3\2\0\10\3\1\161\20\3\4\0"+
    "\2\3\2\0\1\3\2\0\12\3\1\162\16\3\4\0"+
    "\2\3\2\0\1\3\2\0\13\3\1\163\15\3\4\0"+
    "\2\3\2\0\1\3\2\0\7\3\1\164\21\3\4\0"+
    "\2\3\2\0\1\3\2\0\14\3\1\54\14\3\4\0"+
    "\2\3\2\0\1\3\2\0\22\3\1\165\6\3\4\0"+
    "\2\3\2\0\1\3\2\0\21\3\1\166\7\3\4\0"+
    "\2\3\2\0\1\3\2\0\5\3\1\167\23\3\4\0"+
    "\2\3\2\0\1\3\2\0\17\3\1\170\11\3\4\0"+
    "\2\3\2\0\1\3\2\0\7\3\1\171\21\3\4\0"+
    "\2\3\2\0\1\3\2\0\16\3\1\172\12\3\4\0"+
    "\2\3\2\0\1\3\2\0\11\3\1\173\17\3\4\0"+
    "\2\3\2\0\1\3\2\0\17\3\1\55\11\3\4\0"+
    "\2\3\2\0\1\3\2\0\25\3\1\174\3\3\4\0"+
    "\2\3\2\0\1\3\2\0\1\3\1\174\27\3\4\0"+
    "\2\3\2\0\1\3\2\0\12\3\1\175\16\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\176\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\4\3\1\177\24\3\4\0"+
    "\2\3\2\0\1\3\2\0\21\3\1\200\7\3\4\0"+
    "\2\3\2\0\1\3\2\0\2\3\1\201\26\3\4\0"+
    "\2\3\2\0\1\3\2\0\5\3\1\74\23\3\4\0"+
    "\2\3\2\0\1\3\2\0\24\3\1\202\4\3\4\0"+
    "\2\3\2\0\1\3\2\0\1\3\1\54\27\3\4\0"+
    "\2\3\2\0\1\3\2\0\7\3\1\203\21\3\4\0"+
    "\2\3\2\0\1\3\2\0\10\3\1\204\20\3\4\0"+
    "\2\3\2\0\1\3\2\0\11\3\1\205\17\3\4\0"+
    "\2\3\2\0\1\3\2\0\25\3\1\206\3\3\4\0"+
    "\2\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4356];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\21\1\2\11\4\1\2\11\2\1\1\11\24\1"+
    "\1\11\1\0\1\11\1\0\1\11\1\0\20\1\1\11"+
    "\75\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _NginxLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 98) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return NginxElementTypes.CLOSING_BRACE;
          }
        case 15: break;
        case 6: 
          { //the idea is to distinguish:
                                                // 1) asd$ as value "asd$"
                                                // 2) asd$qwe as value "asd" and variable "$qwe"
                                                //thus, I include dollar and tail and cut the tail
                                                //if you find any easier solution - advise me, please
                                                int indexOfDollar = yytext().toString().indexOf("$");
                                                if (indexOfDollar >= 0) {
                                                    yypushback(yylength() - indexOfDollar - 1);
                                                }

                                                return NginxElementTypes.DIRECTIVE_VALUE;
          }
        case 16: break;
        case 3: 
          { return NginxElementTypes.COMMENT;
          }
        case 17: break;
        case 10: 
          { yybegin(YYINITIAL); return NginxElementTypes.OPENING_BRACE;
          }
        case 18: break;
        case 14: 
          { yybegin(DIRECTIVE_VALUE); return NginxElementTypes.LUA_CONTEXT;
          }
        case 19: break;
        case 1: 
          { yybegin(DIRECTIVE_VALUE); return NginxElementTypes.DIRECTIVE_NAME;
          }
        case 20: break;
        case 8: 
          { yybegin(YYINITIAL); return NginxElementTypes.CLOSING_BRACE;
          }
        case 21: break;
        case 2: 
          { return NginxElementTypes.WHITE_SPACE;
          }
        case 22: break;
        case 7: 
          { yybegin(YYINITIAL); return NginxElementTypes.SEMICOLON;
          }
        case 23: break;
        case 11: 
          { yybegin(DIRECTIVE_VALUE); return NginxElementTypes.CONTEXT_NAME;
          }
        case 24: break;
        case 12: 
          { yypushback(1); return NginxElementTypes.VALUE_WHITE_SPACE;
          }
        case 25: break;
        case 4: 
          { return NginxElementTypes.BAD_CHARACTER;
          }
        case 26: break;
        case 13: 
          { return NginxElementTypes.DIRECTIVE_STRING_VALUE;
          }
        case 27: break;
        case 9: 
          { return NginxElementTypes.INNER_VARIABLE;
          }
        case 28: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
